package com.jpp.foods.services.response;

import com.google.gson.annotations.SerializedName;

/**
 * Generic response generated by the server. All the responses from the server
 * should inherit the logic and properties from this class.
 * 
 * @author Juan P. Peretti (peretti.juan@gmail.com)
 * 
 */
public class GenericResponse {


    @SerializedName("meta")
    private ResponseCode mResponseCode;

    public ResponseCode getResponseCode() {
        return mResponseCode;
    }

    public void setResponseCode(ResponseCode mResponseCode) {
        this.mResponseCode = mResponseCode;
    }

}
